const SOLDIERS={Selçuk:{Gulam:115,Kemankeş:135,Selçuk:105,Alparslan:125,Kargılı:160,'Atlı Okçu':225,Sipahi:175,Mancınık:50,Top:60},Hun:{Toygun:125,Kemankeş:145,Tarık:110,Barlas:135,Tunga:175,Talakan:230,Tarkan:195,Mancınık:50,Top:60},Göktürk:{Karabudun:120,Kemankeş:140,Tapukçi:100,'Mavi Kurt':130,Muhafız:150,'Mavi Atlı':200,Kürşad:180,Mancınık:50,Top:60}};
let villages=JSON.parse(localStorage.getItem('umaykut_villages')||'[]'),enemy={race:'',name:'',speed:0},mine={race:'',name:'',speed:0};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('umaykut_villages',JSON.stringify(villages));renderVillages()}
function addVillage(){let name=$('vname').value.trim(),x=$('vx').value.trim(),y=$('vy').value.trim();if(!name||!x||!y)return alert('Köy adı, X ve Y gir.');if(villages.length>=10)return alert('En fazla 10 köy kaydedebilirsin.');villages.push({name,x,y});save();['vname','vx','vy'].forEach(id=>$(id).value='')}
function renderVillages(){let list=$('villages');list.innerHTML=villages.length?villages.map((v,i)=>`<div class="row" style="margin:5px 0"><select><option>${v.name} (${v.x}, ${v.y})</option></select><button class="btn secondary" style="max-width:65px" onclick="villages.splice(${i},1);save()">Sil</button></div>`).join(''):'<div class="empty">Henüz köy kaydedilmedi.</div>';let s=$('sourceVillage');s.innerHTML=villages.length?villages.map((v,i)=>`<option value="${i}">${v.name} — ${v.x}, ${v.y}</option>`).join(''):'<option value="">Köy seç</option>';if(villages.length)s.value='0';let t=$('targetVillage');if(t){t.innerHTML='<option value="">Kayıtlı köy seç...</option>'+villages.map((v,i)=>`<option value="${i}">${v.name} — ${v.x}, ${v.y}</option>`).join('')} }

function syncTargetVillage(){let t=$('targetVillage');if(!t)return;let i=t.value;if(i===''){return}let v=villages[+i];if(!v)return;$('tx').value=v.x;$('ty').value=v.y}

function selectorHTML(kind,race){let st=kind==='enemy'?enemy:mine;race=race||st.race||'Selçuk';return `<div class="chips">${Object.keys(SOLDIERS).map(r=>`<button type="button" class="chip ${r===race?'active':''}" onclick='showRace(${JSON.stringify(kind)},${JSON.stringify(r)})'>${r}</button>`).join('')}</div><div class="soldier-list">${Object.entries(SOLDIERS[race]).map(([n,s])=>`<button type="button" class="soldier-btn" onclick='pick(${JSON.stringify(kind)},${JSON.stringify(race)},${JSON.stringify(n)},${s})'>${n}<strong>${s}</strong></button>`).join('')}</div>`}
function toggleSelector(kind){let el=$(kind==='enemy'?'enemySelector':'mineSelector');el.hidden=!el.hidden;if(!el.hidden)el.innerHTML=selectorHTML(kind)}
function showRace(kind,r){$(kind==='enemy'?'enemySelector':'mineSelector').innerHTML=selectorHTML(kind,r)}
function pick(kind,r,n,s){let st=kind==='enemy'?enemy:mine;Object.assign(st,{race:r,name:n,speed:s});$(kind==='enemy'?'enemyBtn':'mineBtn').textContent=`${n} • ${s}`;$(kind==='enemy'?'enemySelector':'mineSelector').hidden=true}
const YULA_REF_SPEED=89.1,YULA_REF_TIME=26,YULA_REF_DISTANCE=Math.sqrt(20);function dist(x1,y1,x2,y2){return Math.sqrt((x2-x1)**2+(y2-y1)**2)}function sec(x1,y1,x2,y2,s){return Math.round(dist(x1,y1,x2,y2)*(YULA_REF_TIME/YULA_REF_DISTANCE)*(YULA_REF_SPEED/s))}function fmt(v){v=Math.max(0,Math.round(v));let h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=v%60;return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function time(){let h=+$('ah').value,m=+$('am').value,s=+$('as').value;if(h>23||m>59||s>59)throw Error('Saat 00:00:00–23:59:59 aralığında olmalı.');let d=new Date();d.setHours(h,m,s,0);return d}
function ts(d){return d.toLocaleTimeString('tr-TR',{hour12:false})}
function calculate(){try{if(!enemy.speed||!mine.speed)throw Error('Önce düşman ve kendi askerini seç.');let i=+$('sourceVillage').value,v=villages[i];if(!v)throw Error('Senin köyünü seç.');let ex=+$('ex').value,ey=+$('ey').value,a=time(),leg=sec(ex,ey,+v.x,+v.y,enemy.speed);if($('diamond').checked)leg/=2;let dep=new Date(a-leg*1000),ret=new Date(a.getTime()+leg*1000);let own=villages[i];let back=sec(+own.x,+own.y,ex,ey,mine.speed);if($('mineDiamond').checked)back/=2;let send=new Date(ret-back*1000);$('results').innerHTML=`<div class="box"><div class="k">Düşman gidiş</div><div class="v">${fmt(leg)}</div></div><div class="box"><div class="k">Düşman çıkış</div><div class="v">${ts(dep)}</div></div><div class="box"><div class="k">Düşman varış</div><div class="v">${ts(a)}</div></div><div class="box"><div class="k">Düşman dönüş</div><div class="v">${ts(ret)}</div></div><div class="box"><div class="k">Senin yol</div><div class="v">${fmt(back)}</div></div><div class="box full"><div class="k">Senin gönderme saatin</div><div class="v">${ts(send)}</div></div>`}catch(e){alert(e.message)}}
function clearAll(){['ex','ey','tx','ty','ah','am','as'].forEach(id=>$(id).value='');if($('targetVillage'))$('targetVillage').value='';enemy={race:'',name:'',speed:0};mine={race:'',name:'',speed:0};$('enemyBtn').textContent='Asker seç';$('mineBtn').textContent='Asker seç';$('diamond').checked=false;$('mineDiamond').checked=false;$('results').innerHTML='<div class="empty">Hesaplama bekleniyor...</div>'}
renderVillages();
